
package uk.com.megabrew.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListBeersService", targetNamespace = "http://service.megabrew.com.uk/", wsdlLocation = "http://localhost:8180/Products?wsdl")
public class ListBeersService
    extends Service
{

    private final static URL LISTBEERSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTBEERSSERVICE_EXCEPTION;
    private final static QName LISTBEERSSERVICE_QNAME = new QName("http://service.megabrew.com.uk/", "ListBeersService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8180/Products?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTBEERSSERVICE_WSDL_LOCATION = url;
        LISTBEERSSERVICE_EXCEPTION = e;
    }

    public ListBeersService() {
        super(__getWsdlLocation(), LISTBEERSSERVICE_QNAME);
    }

    public ListBeersService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTBEERSSERVICE_QNAME, features);
    }

    public ListBeersService(URL wsdlLocation) {
        super(wsdlLocation, LISTBEERSSERVICE_QNAME);
    }

    public ListBeersService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTBEERSSERVICE_QNAME, features);
    }

    public ListBeersService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListBeersService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListBeers
     */
    @WebEndpoint(name = "ListBeersPort")
    public ListBeers getListBeersPort() {
        return super.getPort(new QName("http://service.megabrew.com.uk/", "ListBeersPort"), ListBeers.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListBeers
     */
    @WebEndpoint(name = "ListBeersPort")
    public ListBeers getListBeersPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.megabrew.com.uk/", "ListBeersPort"), ListBeers.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTBEERSSERVICE_EXCEPTION!= null) {
            throw LISTBEERSSERVICE_EXCEPTION;
        }
        return LISTBEERSSERVICE_WSDL_LOCATION;
    }

}
