
package uk.com.megabrew.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListBeers", targetNamespace = "http://service.megabrew.com.uk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListBeers {


    /**
     * 
     * @return
     *     returns java.util.List<uk.com.megabrew.service.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listBeers", targetNamespace = "http://service.megabrew.com.uk/", className = "uk.com.megabrew.service.ListBeers_Type")
    @ResponseWrapper(localName = "listBeersResponse", targetNamespace = "http://service.megabrew.com.uk/", className = "uk.com.megabrew.service.ListBeersResponse")
    @Action(input = "http://service.megabrew.com.uk/ListBeers/listBeersRequest", output = "http://service.megabrew.com.uk/ListBeers/listBeersResponse")
    public List<Product> listBeers();

}
